In [23]:
# import libraries
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  
from apyori import apriori

In [24]:
# import dataset
dataset = pd.read_csv('Market_Basket_Optimisation.csv',header=None)

In [25]:
# size of dataset
print('Dataset has {} rows and {} columns'.format(dataset.shape[0],dataset.shape[1]))

Dataset has 7501 rows and 20 columns

In [26]:
# display some data
dataset.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# convert dataset into list of list for each transaction
transactions = []
for i in range(0,dataset.shape[0]):
    transactions.append([str(dataset.values[i,j]) for j in range(0,dataset.shape[1])])

In [31]:
# training apriori on dataset
rules = apriori(transactions,min_support=0.003,min_confidence=0.2, min_lift=3, min_length=2)

In [32]:
# view result in list format
rules = list(rules)

In [33]:
for item in rules:
    # first index of the inner list
    # Contains base item and add item
    pair = item[0] 
    items = [x for x in pair]
    print("Rule: " + items[0] + " ----> " + items[1])

    #second index of the inner list
    print("Support: " + str(item[1]))

    #third index of the list located at 0th
    #of the third index of the inner list

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("\n\n")

Rule: fromage blanc ----> honey
Support: 0.003332888948140248
Confidence: 0.2450980392156863
Lift: 5.164270764485569



Rule: nan ----> fromage blanc
Support: 0.003332888948140248
Confidence: 0.2450980392156863
Lift: 5.164270764485569



Rule: olive oil ----> whole wheat pasta
Support: 0.0038661511798426876
Confidence: 0.4027777777777778
Lift: 6.115862573099416



Rule: mineral water ----> soup
Support: 0.0030662578322890282
Confidence: 0.27710843373493976
Lift: 5.484407286136631



Rule: olive oil ----> nan
Support: 0.0038661511798426876
Confidence: 0.4027777777777778
Lift: 6.115862573099416



Rule: mineral water ----> milk
Support: 0.0030662578322890282
Confidence: 0.27710843373493976
Lift: 5.484407286136631